spring:
  datasource:
    url: jdbc:postgresql://localhost:1212/taskflow_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

